name: GHA

on:
 push:
  paths:
  - '.github/workflows/*.yml'
  - '**/action.yml'
 pull_request:
  paths:
  - '.github/workflows/*.yml'
  - '**/action.yml'

defaults:
 run:
  shell: bash

jobs:
 actionlint:
  runs-on: ubuntu-latest
  steps:

  - uses: actions/checkout@v4

  - uses: actions/setup-go@v5

  - run: go install github.com/rhysd/actionlint/cmd/actionlint@latest

  - run: actionlint -color
