name: Go

on:
 push:
  paths:
  - '.github/workflows/go.yml'
  - 'go.mod'
  - 'go.sum'
  - '**.go'
 pull_request:
  paths:
  - '.github/workflows/go.yml'
  - 'go.mod'
  - 'go.sum'
  - '**.go'

defaults:
 run:
  shell: bash

jobs:
 Build:
  runs-on: ${{ matrix.os }}
  outputs:
   go-version: ${{ steps.setup-go.outputs.go-version }}

  strategy:
   fail-fast: false
   matrix:
    os: [ubuntu-latest, windows-latest]

  steps:

  - uses: actions/checkout@v4

  - id:   setup-go
    uses: actions/setup-go@v5
    with:
     go-version-file: 'go.mod'
     check-latest:    true

  - run: go version

  - run: go mod download -x

  - run: go build -v -trimpath -o bin/ ./...

 Generate:
  needs: Build
  runs-on: ${{ matrix.os }}
  strategy:
   fail-fast: false
   matrix:
    os: [ubuntu-latest, windows-latest]

  steps:

  - uses: actions/checkout@v4

  - uses: actions/setup-go@v5
    with:
     go-version-file: 'go.mod'
     check-latest:    false
     cache:           false

  - run: go version

  - run: go generate makefile.go

 Test:
  needs: Build
  runs-on: ${{ matrix.os }}
  strategy:
   fail-fast: false
   matrix:
    os: [ubuntu-latest, windows-latest]

  steps:

  - uses: actions/checkout@v4

  - uses: actions/setup-go@v5
    with:
     go-version:   ${{ needs.Build.outputs.go-version }}
     check-latest: true

  - run: go version

  - run: go mod download -x

  - run: go test -v -vet=all -trimpath ./...
